" Theme
syntax on
color dracula

" Indentation & Tabs
set autoindent
set smartindent
set tabstop=2
set shiftwidth=4

" Display & format
set number
set textwidth=80
set wrapmargin=2
set showmatch

" Search
set hlsearch
set incsearch
set ignorecase
set smartcase

" Browse & Scroll
set scrolloff=5
set laststatus=2

" Miscellaneous
set nobackup
set noswapfile
set autochdir
set undofile
set errorbells
set visualbell
